version: "3.3"
services:
  factorio:
    image: kkusch91/factorio:latest
    deploy:
      replicas: 1
    ports:
      - "34197:34197/udp"
    volumes:
      - ./server/server-settings.example.json:/opt/factorio/server-settings.json
      - ./server/saves:/opt/factorio/saves
      - ./server/mods:/opt/factorio/mods
