# This is a basic workflow to help you get started with Actions

name: Publish Factorio Image by TagVersion

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set env
        env:
          TARGET_VERSION: ${GITHUB_REF#refs/*/}
        run: |
          echo "RELEASE_VERSION=$TARGET_VERSION" >> $GITHUB_ENV
          echo "LOCAL_FILENAME=factorio_headless_x64.tar.xz" >> $GITHUB_ENV
          echo "DOWNLOAD_URL=https://www.factorio.com/get-download/$TARGET_VERSION/headless/linux64" >> $GITHUB_ENV

      - name: "download factorio headless server binary"
        run: "wget ${{ env.DOWNLOAD_URL }} -O ${{ env.LOCAL_FILENAME }}"
      
      - name: "docker build"
        run: "docker build -t kkusch91/factorio:${{ env.RELEASE_VERSION }} -t kkusch91/factorio:latest ."

      - name: "docker-login" 
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD"

      - name: "push to dockerhub"
        run: |
          docker push kkusch91/factorio:${{ env.RELEASE_VERSION }}
          docker push kkusch91/factorio:latest
